name: Build and Release Jar

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Extract Tag Name
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./target/simplewebservice-${{ env.VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
